name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: CI Tasks
        run: make ci
      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
            github-token: ${{ secrets.github_token }}
            path-to-lcov: coverage.lcov        